name: zorphy_annotation_example
description: Example usage of zorphy_annotation package
version: 1.0.0
publish_to: none

environment:
  sdk: "^3.8.0"

dependencies:
  zorphy_annotation:
    path: ../
  json_annotation: ^4.10.0

dev_dependencies:
  build_runner: ^2.11.0
  json_serializable: ^6.8.0
  lints: ^3.0.0
  zorphy:
    path: ../../zorphy
