name: zorphy_example
description: Example usage of the zorphy package
publish_to: "none"

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  zorphy_annotation: ^1.3.2
  json_annotation: ^4.10.0

dev_dependencies:
  zorphy:
    path: ../
  build_runner: ^2.11.0
  json_serializable: ^6.12.0