name: test_app
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  zorphy_annotation:
    path: ../../zorphy_annotation
dev_dependencies:
  build_runner: ^2.4.0
  zorphy:
    path: ../../zorphy
  json_serializable: ^6.7.0
